### ISSUE TITLE
No validation when adding ValidateNumber scalar

### ISSUE THREAD

**Issue by JeremiFerre** [alexanderVu/apollo-server-constraint-directive#11]
**Describe the bug**
Constraint validations are not triggered when adding `scalar ValidateNumber` in GraphQL schema. Removing it make the API working with validations, but GraphQL tools such as GraphQL codegen are not working because it doesn't recognize ValidateNumber scalar. 

**To Reproduce**
```gql
scalar ValidateNumber

directive @constraint(
    # String constraints
    minLength: Int
    maxLength: Int
    startsWith: String
    endsWith: String
    notContains: String
    pattern: String
    format: String

    # Number constraints
    min: Int
    max: Int
    exclusiveMin: Int
    exclusiveMax: Int
    multipleOf: Int
) on INPUT_FIELD_DEFINITION
```

**Expected behavior**
Graphql constraint directive should be called with `scalar ValidateNumber` defined in the schema.

**Additional context**
After debugging into the library, it seems that @constraint directive is actually detected, and the wrapType method is called. But when making a GraphQL query or mutation with wrong inputs, the custom ValidateNumber parseLitteral or parseValue method is not called.

**Comment by JeremiFerre** [comment]
It seems https://github.com/confuser/graphql-constraint-directive/issues/2 solved this problem. Using a custom scalar wrapping the type directly is not working anymore. @confuser solved it by using schemaTransform and providing his own typeDefs.

**Comment by confuser** [comment]
Thanks for the ping @JeremiFerre, the original package resolves this issue, and is fully compatible with apollo v2 so not sure the reason for this fork but if there's anything missing happy to discuss/open to PRs.

**Comment by JeremiFerre** [comment]
Yeah I've switched to the original package and everything works great. Thank you for your quick answer !
